ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_RESTORED';
